name = "drive"
main = "src/index.js"
compatibility_date = "2023-02-03"
workers_dev = true
account_id = "6b019df5062e31c59e84dcaffebd4866"
kv_namespaces = [
    { binding = "BUCKET", preview_id = "f61ca993889844aebb976cdb1091fc83", id = "b0ce1de83f62420799340a139687e242" }
]

[env.staging]
name = "drive-staging"
